// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyWithResolvedRefs(arg1:string):Promise<string>;

export function Evaluate(arg1:string):Promise<Array<main.EvalResult>>;

export function GetVersion():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFileDialog():Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
