// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentFile(arg1) {
  return window['go']['main']['App']['AddRecentFile'](arg1);
}

export function AdjustReferences(arg1, arg2) {
  return window['go']['main']['App']['AdjustReferences'](arg1, arg2);
}

export function AutoSave(arg1, arg2) {
  return window['go']['main']['App']['AutoSave'](arg1, arg2);
}

export function CopyWithResolvedRefs(arg1) {
  return window['go']['main']['App']['CopyWithResolvedRefs'](arg1);
}

export function Evaluate(arg1) {
  return window['go']['main']['App']['Evaluate'](arg1);
}

export function GetLastFile() {
  return window['go']['main']['App']['GetLastFile']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFileDialog() {
  return window['go']['main']['App']['SaveFileDialog']();
}

export function SetUnsavedState(arg1, arg2) {
  return window['go']['main']['App']['SetUnsavedState'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
