// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRecentFile(arg1:string):Promise<void>;

export function AdjustReferences(arg1:string,arg2:string):Promise<string>;

export function AutoSave(arg1:string,arg2:string):Promise<void>;

export function CopyWithResolvedRefs(arg1:string):Promise<string>;

export function Evaluate(arg1:string,arg2:number):Promise<Array<main.EvalResult>>;

export function EvaluateLines(arg1:string,arg2:number):Promise<Array<main.EvalResult>>;

export function FindDependentLines(arg1:string,arg2:number):Promise<Array<number>>;

export function GetLastFile():Promise<string>;

export function GetRecentFiles():Promise<Array<string>>;

export function GetVersion():Promise<string>;

export function HasLineResult(arg1:string):Promise<boolean>;

export function OpenFileDialog():Promise<string>;

export function Quit():Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFileDialog():Promise<string>;

export function SetUnsavedState(arg1:boolean,arg2:string):Promise<void>;

export function ShowInfoDialog(arg1:string,arg2:string):Promise<void>;

export function StripAndEvalReferencingLines(arg1:string):Promise<string>;

export function StripLineResult(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
